export const ACTION_TYPE = {
    SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SET_PRODUCTS: 'SET_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART',
    SET_OUTFIT_DATA: 'SET_OUTFIT_DATA',
    ADD_TO_COMBINER: 'ADD_TO_COMBINER',
    REMOVE_FROM_COMBINER: 'REMOVE_FROM_COMBINER'
    
}